apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: app-backstage-example for testing - named ${{ values.app_name }}
  annotations:
    github.com/project-slug: carlosrovaris/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental